### ISSUE TITLE
500 Internal error encountered in view/train ("function not exported" in gpu-memory-series)

### ISSUE THREAD

**Issue by saket424** [guildai/_guild-legacy#12]
Attached are the associated console logs and guild logs when I try to view a training of the mnist guild-example, I get a 500 Internal error. Looking for your assistance to get past this issue as I am clueless on where to start . Thanks in advance

console logs from http://localhost:6333
This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead  iron-shadow-flex-layout.html.js:2:3
This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead  iron-flex-layout.html.js:2:3
XMLHttpRequest { onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, responseURL: "http://localhost:6333/data/settings", status: 500, statusText: "Internal Server Error", responseType: "", response: "Server error " }  data.js:39:17
XMLHttpRequest { onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, responseURL: "http://localhost:6333/data/project", status: 500, statusText: "Internal Server Error", responseType: "", response: "Server error " }  data.js:39:17
XMLHttpRequest { onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, responseURL: "http://localhost:6333/data/runs", status: 500, statusText: "Internal Server Error", responseType: "", response: "Server error " }

--------------------------------------------------

(tf+gpu+py2.7) anand@Alien15:~/tf-stuff/guild-examples/mnist$ guild view
Guild View running on port 6333

=ERROR REPORT==== 30-Jun-2017::10:55:21 ===
** Generic server <0.68.0> terminating 
** Last message in was {'$call',{#Fun<guild_view.0.92108128>,[]}}
** When Server state == {state,guild_view,
                               {state,".",
                                      ["./runs"],
                                      #{refreshInterval => 5,
                                        tensorboard => #{demo => false,port => 58005}}},
                               undefined}
** Reason for termination == 
** {'function not exported',
       [{lists,join,[9,["template","gpu-memory-series"]],[]},
        {guild_view,section_path_key,1,
            [{file,
                 "/home/anand/tf-stuff/guild/build/default/lib/guild/src/guild_view.erl"},
             {line,96}]},
        {guild_view,format_project_section,1,
            [{file,
                 "/home/anand/tf-stuff/guild/build/default/lib/guild/src/guild_view.erl"},
             {line,93}]},
        {guild_view,'-format_project_sections/1-lc$^0/1-0-',1,
            [{file,
                 "/home/anand/tf-stuff/guild/build/default/lib/guild/src/guild_view.erl"},
             {line,89}]},
        {guild_view,format_project_sections,1,
            [{file,
                 "/home/anand/tf-stuff/guild/build/default/lib/guild/src/guild_view.erl"},
             {line,89}]},
        {guild_view,format_project,1,
            [{file,
                 "/home/anand/tf-stuff/guild/build/default/lib/guild/src/guild_view.erl"},
             {line,85}]},
        {guild_view,handle_msg,3,
            [{file,
                 "/home/anand/tf-stuff/guild/build/default/lib/guild/src/guild_view.erl"},
             {line,66}]},
        {e2_service,dispatch_call,3,
            [{file,
                 "/home/anand/tf-stuff/guild/build/default/lib/e2/src/e2_service.erl"},
             {line,206}]}]}

=ERROR REPORT==== 30-Jun-2017::10:55:21 ===
{handler_error,<0.386.0>,
    {app_error,
        {{undef,
             [{lists,join,[9,["template","gpu-memory-series"]],[]},
              {guild_view,section_path_key,1,
                  [{file,
                       "/home/anand/tf-stuff/guild/build/default/lib/guild/src/guild_view.erl"},
                   {line,96}]},
              {guild_view,format_project_section,1,
                  [{file,
                       "/home/anand/tf-stuff/guild/build/default/lib/guild/src/guild_view.erl"},
                   {line,93}]},
              {guild_view,'-format_project_sections/1-lc$^0/1-0-',1,
                  [{file,
                       "/home/anand/tf-stuff/guild/build/default/lib/guild/src/guild_view.erl"},
                   {line,89}]},
              {guild_view,format_project_sections,1,
                  [{file,
                       "/home/anand/tf-stuff/guild/build/default/lib/guild/src/guild_view.erl"},
                   {line,89}]},
              {guild_view,format_project,1,
                  [{file,
                       "/home/anand/tf-stuff/guild/build/default/lib/guild/src/guild_view.erl"},
                   {line,85}]},
              {guild_view,handle_msg,3,
                  [{file,
                       "/home/anand/tf-stuff/guild/build/default/lib/guild/src/guild_view.erl"},
                   {line,66}]},
              {e2_service,dispatch_call,3,
                  [{file,
                       "/home/anand/tf-stuff/guild/build/default/lib/e2/src/e2_service.erl"},
                   {line,206}]}]},
         {gen_server,call,
             [<0.68.0>,
              {'$call',{#Fun<guild_view.0.92108128>,[]}},
              infinity]}}}}

=ERROR REPORT==== 30-Jun-2017::10:55:21 ===
{handler_error,<0.387.0>,
    {app_error,
        {{undef,
             [{lists,join,[9,["template","gpu-memory-series"]],[]},
              {guild_view,section_path_key,1,
                  [{file,
                       "/home/anand/tf-stuff/guild/build/default/lib/guild/src/guild_view.erl"},
                   {line,96}]},
              {guild_view,format_project_section,1,
                  [{file,
                       "/home/anand/tf-stuff/guild/build/default/lib/guild/src/guild_view.erl"},
                   {line,93}]},
              {guild_view,'-format_project_sections/1-lc$^0/1-0-',1,
                  [{file,
                       "/home/anand/tf-stuff/guild/build/default/lib/guild/src/guild_view.erl"},
                   {line,89}]},
              {guild_view,format_project_sections,1,
                  [{file,
                       "/home/anand/tf-stuff/guild/build/default/lib/guild/src/guild_view.erl"},
                   {line,89}]},
              {guild_view,format_project,1,
                  [{file,
                       "/home/anand/tf-stuff/guild/build/default/lib/guild/src/guild_view.erl"},
                   {line,85}]},
              {guild_view,handle_msg,3,
                  [{file,
                       "/home/anand/tf-stuff/guild/build/default/lib/guild/src/guild_view.erl"},
                   {line,66}]},
              {e2_service,dispatch_call,3,
                  [{file,
                       "/home/anand/tf-stuff/guild/build/default/lib/e2/src/e2_service.erl"},
                   {line,206}]}]},
         {gen_server,call,
             [<0.68.0>,
              {'$call',{#Fun<guild_view.1.92108128>,[]}},
              infinity]}}}}

=ERROR REPORT==== 30-Jun-2017::10:55:21 ===
{handler_error,<0.385.0>,
    {app_error,
        {noproc,
            {gen_server,call,
                [<0.68.0>,
                 {'$call',{#Fun<guild_view.1.92108128>,[]}},
                 infinity]}}}}

=ERROR REPORT==== 30-Jun-2017::10:55:26 ===
{handler_error,<0.389.0>,
    {app_error,
        {noproc,
            {gen_server,call,
                [<0.68.0>,
                 {'$call',{#Fun<guild_view.1.92108128>,[]}},
                 infinity]}}}}

=ERROR REPORT==== 30-Jun-2017::10:55:31 ===

**Comment by gar1t** [comment]
Did you install this from source, or is this a release? Could you run:

    guild --version

and let me know what it says? Thanks!

**Comment by saket424** [comment]
I installed from git source

guild --version
guild 0.0.0 (ed55875)

I am on the chicagoai slack channel now

**Comment by gar1t** [comment]
This issue was related to an OTP 19 dependency that slipped in. That's been fixed in f9bd24ca.
